### ISSUE TITLE
definitions to structures not properly handled.

### ISSUE THREAD

**Issue by SourceCodeDeleted** [Lambosaurus/py-c-preprocessor#7]
here is what I get when I try to parse 

`#define AFLASH_0  (*(volatile struct AFLASH_tag *)      0xC3F33000UL)

```
from preprocessor import Preprocessor
p = Preprocessor()
p.include('/home/ubuntu/works/perf_definitions/MRC7765.h')
print(p.evaluate('AFLASH')) 
```

```
  result = eval(expr)
  File "<string>", line 1
    (*(AFLASH_tag *)      0xC3F44000UL)
                   ^
SyntaxError: invalid syntax
```

**Comment by Lambosaurus** [comment]
Yes - I would expect evaluation of that expression to fail - as it has very limited evaluation capabilites.
It will expand correctly however, try `print(p.expand('AFLASH'))` , and see if that is what you expect.

Otherwise, could you tell me what result you did expect, and also supply me your source header?

**Comment by SourceCodeDeleted** [comment]
Actually , I think this will work. I will double check and should I not respond in a couple of days , then we can close this.

**Comment by Lambosaurus** [comment]
I am marking this closed.

I have updated the readme to include an example of the `.expand` method to prevent confusion in future: a633e960155b2f60bbe4b6cf66f68b6d5a0a92be

Feel free to let me know if there are any features that would help you out.
